### ISSUE TITLE
Add support for ROS2 Jazzy

### ISSUE THREAD

**Issue by MuhamedAgic** [tuw-robotics/stage_ros2#1]
Hello,

I really like this stage solution, it works well for ros humble!
Could you add support for ROS2 Jazzy?
This distro recently rolled out and has long term support like humble.
It would be much appreciated!

Cheers!

**Comment by maxbader** [comment]
We are working on it. Please give us some time

**Comment by MuhamedAgic** [comment]
I'm sorry, didn't mean to put pressure on you!
Thank you for the fast response, i'm looking forward to it :) !

**Comment by maxbader** [comment]
We are now ready for Jazzy

**Comment by ksatyaki** [comment]
Please change the ROS2 dependency of tf to tf2!
:-)
